version: "3.1"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "ecto_class"
      POSTGRES_PASSWORD: "ecto_class"
  adminer:
    image: adminer
    ports:
      - 8080:8080
